apiVersion: v1
kind: Pod
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
spec:
  hostname: jenkins-master
  containers:
  - name: jenkins-master
    image: 127.0.0.1:32000/jenkins-master
    env:
      - name:  JAVA_OPTS
        value: -Djenkins.install.runSetupWizard=false
    ports:
      - name: http-port
        containerPort: 8080
      - name: jnlp-port
        containerPort: 50000
    volumeMounts:
      - name: jenkins-config
        mountPath: "/var/jenkins_home"
  volumes:
    - name: jenkins-config
      hostPath:
        path: /mnt/kubernetes/jenkins/config
        type: Directory
