apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30880
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins-master
